### ISSUE TITLE
Setup greenkeeper.io

### ISSUE THREAD

**Issue by Inkdpixels** [neos/eslint-config-neos#2] opened 2016-08-08 08:04 UTC

**Comment by markusguenther** [comment] 2018-01-07 16:10
Hmm don`t get me wrong ... I like the idea and maybe I just miss something. But updating the libraries here is not that complicated. The problem is, that we break possibly the neos-ui and you can not check here if something breaks.

You also have the problem that eslint for instance is used in the build-essentials and here. So you need to keep them in sync because the neos-ui always uses eslint from the build-essentials.

But if you get me some insights I can try to help you :)

**Comment by Inkdpixels** [comment] 2018-01-07 19:16
@markusguenther Breaking stuff is pretty much impossible Since this package would need to get released in the first place and updated in neos ui to take effect. :)

That Said, I think in the Long run it would make more Sense to move this package into the Neos Ui mono repo and enable either greenkeeper(if they support Mono repos at that point) or renovate to update the dependencies there all together. This reduces the possabilities of Security vulnabilities and the maintanance overhead a lot and we can be 100% sure that things work as expected after dependency updates. wdyt?

**Comment by markusguenther** [comment] 2018-01-07 19:21
Ok good point.

Would be pragmatic to have this repository also in the react-ui. On the other hand we already have so much stuff in the repository that it also feels good to have a smaller chunk.

ATM I don`t think that it is harder to maintain. For local dev stuff I just add my on branch and use it.
But then can also happen thinks like yesterday.

But never used greenkeeper. Only read the stuff on their webpage and it sounds promising :D

**Comment by markusguenther** [comment] 2020-01-03 14:13
Guess we can close this. Also think dependabot is also a better alternative right now and it aquired by github.

**Closed by markusguenther** 2020-01-03 14:13 UTC
Labels: enhancement
